pd-rs/crank

src/config.rs
src/main.rs

Need for cases where SDK is in custom place installed.

Add SDK config support

---

README.md
src/main.rs

Get rid of `xbuild` and use nightly `build-std` builtin feature.
Closes #7.
@rtsuk, please test native build on the real device if possible.

Use `build-std` feature

---

.github/workflows/tests.yml
Cargo.lock
rust-toolchain
src/main.rs

The [official docs](https://sdk.play.date/1.9.3/Inside%20Playdate.html#_set_playdate_sdk_path_environment_variable) say to set `PLAYDATE_SDK_PATH` so it should be a pretty reliable way to find the SDK.
I've also got [another branch](https://github.com/skeet70/crank/tree/linux-build-custom-target) off this one that makes everything work for my specific setup, but I haven't generalized it (my `target` is in a `/tmp/` ramdisk). The one piece that may be generally useful there is [this change](https://github.com/skeet70/crank/blob/linux-build-custom-target/src/main.rs#L461) which makes the run command use the SDK path too (`open` doesn't exist on my distro).
With the changes in both those branches done, I can confirm everything in `hello_world` (and `crankstart-klondike`) works on Arch Linux …

Check for the env var mentioned by playdate docs

---

.github/workflows/tests.yml

SDK 1.9.3+ is distributed as a .zip file for macOS with a "PlaydateSDK.pkg" file inside of it

Fix macOS CI to use .zip for sdk download

---

.github/README.md
.github/workflows/release.yml
.github/workflows/tagger.yml
.github/workflows/tests.yml

- Improved tests-workflow: use gh-action to get the SDK;
- Added readme that describes new pipelines and usage.
Feel free to suggest changes and fix my "broken English" for better wording.

CI: add release workflow

---

.github/workflows/tests.yml
src/main.rs

This PR adds better Linux support to Crank with the following minor changes:
* Assume `arm-none-eabi-gcc` and `arm-none-eabi-objcopy` are in PATH env var instead of using static paths on Linux
* Add support for specifying `PLAYDATE_SERIAL_DEVICE` and `PLAYDATE_MOUNT_POINT` with reasonable defaults on Linux (note: untested since I've not received my Playdate yet)
* Use `eject` command to eject the Playdate on non-macOS (note: untested since I've not received my Playdate yet)
* Assume `PlaydateSimulator` is in PATH on non-macOS instead of using the macOS-specific `open -a`
* Reveal pdx via `xdg-open` on Linux (that tool will use whatever the default file manager is, but does not natively support selecting a particular file)
The CI should pass once pd-rs/get-playdate-sdk#5 is merged or the …

Add Linux support

---

src/main.rs

This PR adds support for specifying game data in Crank.toml and having crank generate pdxinfo files from it as specified by the manual. It additionally gives the game title from the metadata precedence over `to_title_case(&target_name)` when deciding the destination path for the pdx and makes `assets` optional in Crank.toml. See https://github.com/lilyinstarlight/crankstart/commit/8b59dc05b1f46f468a924ef58a6b2b44f9cef476 for an example of how this can be used
Fixes #21

Add support for generating pdxinfo files from metadata in Crank.toml

---

src/main.rs

I just got my new playdate and was having a tough time getting `crank` to successfully copy files to the playdate.
I tracked it down to a timing issue. It seems like the PLAYDATE volume would be mounted but not fully available. This fix changes the code to wait until the "Games" folder can be read.
I also removed another arbitrary sleep that I presume was there to prevent something similar? The new check should more reliably handle whatever that other sleep was for.
*Edit:* I'm deploying from a Mac

Fix intermittent (but frequent) failure to copy files

---

Cargo.toml
src/main.rs

This addresses some of the comments in #12.
* On Linux, don't wait for `modem_path` to disappear after initiating data disk mode, since (at least for me) it remains available.
* On Linux, sleep before issuing `pdutil run`.  Without a wait it was failing.  I based this on the Windows case, but on my machine it required 1s instead of 500ms.
* Print a message about pressing 'A' to exit Data Disk mode, after ejecting the Playdate, because I don't think the message on the Playdate screen is very clear about it, and crank is just waiting for the user.
* Print a message about mounting the Playdate, in case the OS doesn't do so automatically.
For the last two items, I chose a `println` rather than a log message because logging isn't enabled in crank by default - I didn't want to change the …

Improve Linux experience for `crank run --device`

---

README.md
src/main.rs

Fixes the error discussed at pd-rs/crankstart#30 by removing the need to build std from source. That does appear to be a bug caused from a regression in rust nightly, but this may still be a better option to lower the reliance on nightly rust.
Nightly is still necessary for the `aloc` feature, update readme to accomodate.

Removed need for `-Z build-std`

---

Cargo.lock
Cargo.toml
src/main.rs

```
This will use the /dev/serial/by-id/usb-Panic_Inc_Playdate_PDU1-*
symlink to find the appropriate serial device, if possible.  If the
PLAYDATE_SERIAL_DEVICE variable is set, that will take precedence.  If
multiple Playdate devices are found, the user is told, and the first is
used.  If none are found, the same /dev/ttyACM0 backup will be used.
```
This should eliminate the issue of a new crank user on Linux having to set `PLAYDATE_SERIAL_DEVICE` and having a bit of trouble getting started.  Other devices can use `/dev/ttyACM0`, like my keyboard, so I ran into this.
Should address the Linux case for #24.
I tested the following cases on Linux:
* No `--run` - the simulator ran the game OK.
* With `--run`, it found the correct (non-default) device and ran the game OK.
* If I force the …

On Linux, find the Playdate serial device if possible

---

README.md

This had me stuck briefly today - the existing command in the README installs the target for your default toolchain, which for many people will be stable, not nightly, and then nightly builds initiated from crank won't have the target available.  This change clarifies the command so that the target is added for nightly specifically.

Clarify that target must be added to nightly

---

Cargo.lock
Cargo.toml
src/main.rs

related issue: [crankstart #45](https://github.com/pd-rs/crankstart/issues/45)
Note: This is MVP, highly need testing and reviewing. 🙄

Support hardware revB & SDK v2.0

---

README.md

Better README.  Nightly toolchain isn't needed by crank, just crankstart

Better README, nightly not required

---

src/main.rs

The method for running the PlaydateSimulator on Linux assumes that it's in your PATH. The desktop file that gets set up from the setup.sh script in the linux Playdate SDK just executes it from the SDK path, so I figure it's probably safe to do it the same way

get the sdk path to find the executable on linux

---

Cargo.lock
Cargo.toml

Fixes a build error caused by the `zip-extensions` 0.6.2 release, which puts `zip` 0.6 in their public API. This is a breaking change from 0.6.1, which depended on `zip` 0.5.
See: https://github.com/matzefriedrich/zip-extensions-rs/issues/9#issuecomment-1706010715
This PR blocks #48, #49, and #51.

Update zip dependency

---

README.md
src/main.rs

Looks like the compiler path changed in recent versions. I'm using Version `12.3.Rel1`, released July 28, 2023.
https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
Possible fix for #44?

Fix ARM compiler path on Windows

---

src/main.rs

Self explanatory. Allows passing feature flags to Cargo.
Blocked by #50

Add support for Cargo feature flags

---

src/main.rs

The library is written with hyphens replaced with underscores.
----
Example that demonstrates the bug:
`Cargo.toml`:
```toml
[package]
name = "hello-world"
```
`Crank.toml`:
```toml
[[target]]
name = "hello-world"
[target.metadata]
name = "Hello World"
version = "0.1.0"
```
```
$ RUST_LOG=debug crank build --release --example hello-world
DEBUG crank > copy: "C:\\Users\\jay\\other-projects\\crankstart\\target\\release\\examples/hello-world.dll" -> "C:\\Users\\jay\\other-projects\\crankstart\\target\\Hello World\\pdex.dll"
Error: The system cannot find the file specified. (os error 2)
```
```
$ ls -la target/release/examples/*.dll
-rwxr-xr-x 2 jay 197121 139264 Aug 26 17:58 target/release/examples/hello_world.dll*
-rwxr-xr-x 2 jay 197121 139264 Aug 26 17:58 …
```

Fix "file not found" error when the crate name contains hyphens

---

src/main.rs

Builds with `-Z build-std-features=panic_immediate_abort` to ensure the `core::panicking` plumbing is stripped.
See: https://github.com/rust-lang/rust/pull/55011
Adds `-Cpanic=abort` to RUSTFLAGS so that build profiles do not need to specify `panic = "abort"` in Cargo.toml. This can potentially allow simulator builds to customize panics. (Maybe printing to the console and stopping the event loop, for instance. But this work is TBD.)
Fixes https://github.com/pd-rs/crankstart/discussions/66

Fix linker error: undefined symbol `core::panicking::panic`

---

src/main.rs

Hi there! I've been working on a Playdate game in rust for the last 9 months using crankstart. Thanks for all the work on this project which has made that possible! I have a bunch of changes to both [crankstart](https://github.com/jder/crankstart) and [crank](https://github.com/jder/crank), some of which are probably useful to others, so I'm planning to start sending some back upstream. Here's the first! Changelog below:
--
The FPU settings for C code are `-mfpu=fpv5-sp-d16`, the `-sp-` part means that double precision floating point is unsupported. The [rust docs](https://doc.rust-lang.org/nightly/rustc/platform-support/thumbv7em-none-eabi.html#table-of-supported-cpus-for-thumbv7em-none-eabihf) show that getting this same effect from rustc-emitted code requires this additional target …

Make rust emitted code compatible with Rev A Playdate hardware
